use std::pin::Pin;
use std::sync::Arc;
use std::time::Instant;
use tonic::{transport::Server, Request, Response, Status};

use proj1::chatroom_data::auth_server::{Auth, AuthServer};
use proj1::chatroom_data::{CreationResult, LoginRequest, LoginResult, LogoutRequest, LogoutResult, User};
use tokio::sync::mpsc;
use tokio_stream::{wrappers::ReceiverStream, Stream, StreamExt};

use proj1::chatroom_data::chat_server::{Chat, ChatServer};
//use chat_server::{HistoryRequest, HistoryResult, MessagePacket, MessageSendResult};
use proj1::chatroom_data::MessagePacket;

//this mod "holds" all the proto defs that get generated by the include_proto!
//proc macro at compile time. this is why the use statements above it start with this name
/*pub mod chat_server {
    tonic::include_proto!("chatroom"); // The string specified here must match the proto package name
}*/

#[derive(Debug, Default, Copy, Clone)]
pub struct ChatServerImpl {}

#[tonic::async_trait]
impl Auth for ChatServerImpl {
    async fn login(
        &self,
        request: Request<LoginRequest>, // Accept request of type HelloRequest
    ) -> Result<Response<LoginResult>, Status> {
        Ok(Response::new(LoginResult {}))
    }
    async fn create_user(
        &self,
        request: Request<User>,
    ) -> Result<Response<CreationResult>, Status> {
        Ok(Response::new(CreationResult {}))
    }
    async fn logout(
        &self,
        request: Request<LogoutRequest>,
    ) -> Result<Response<LogoutResult>, Status> {
        Ok(Response::new(LogoutResult {}))
    }
}
#[tonic::async_trait]
impl Chat for ChatServerImpl {
    type chatlinkStream =
        Pin<Box<dyn Stream<Item = Result<MessagePacket, Status>> + Send + 'static>>;

    /*async fn send_message(
        &self,
        request: Request<MessagePacket>,
    ) -> Result<Response<MessageSendResult>, Status> {
        Ok(Response::new(chat_server::MessageSendResult {}))
    }
    async fn get_history(
        &self,
        request: Request<HistoryRequest>,
    ) -> Result<Response<HistoryResult>, Status> {
        Ok(Response::new(chat_server::HistoryResult {}))
        }*/

    async fn chatlink(
        &self,
        request: Request<tonic::Streaming<MessagePacket>>,
    ) -> Result<Response<Self::chatlinkStream>, Status> {
        println!("entering chatlink function in server");
        let mut stream = request.into_inner();

        let output = async_stream::stream! {
            while let Some(note) = stream.next().await {
                println!("got a message");
                yield Ok(note.clone().unwrap());
                //yield Ok(MessagePacket::new("guh".to_string()));
            }


        };
        Ok(Response::new(Box::pin(output) as Self::chatlinkStream))
    }
}



#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse()?;
    let chatroom = ChatServerImpl::default();

    Server::builder()
        .add_service(AuthServer::new(chatroom))
        .add_service(ChatServer::new(chatroom))
        .serve(addr)
        .await?;

    Ok(())
}
